### ISSUE TITLE
But where is your doctrine credentials config?

### ISSUE THREAD

**Issue by adoshem** [andrebian-solucoes-web/zf-base#1]
I see inside the user module config there is a call for doctrine but i dont see any user credentials passed to it? where do i put my user credentials?

**Comment by andrebian** [comment]
Sorry my mistake. This project is still in development and I forgot to put all needed files. By the way, I'll create docs for startup and maintenance.

At this moment, I just placed the sample for the Doctrine ORM connection: https://github.com/andrebian-solucoes-web/zf-base/commit/adfa75a8af6722ee531f93bb40a7762fcbb1f737

**Comment by adoshem** [comment]
Great looking forward to it.

**Comment by andrebian** [comment]
Can I close this issue?
